### ISSUE TITLE
OSError: [Errno 16] Device or resource busy: 'machine-id'

### ISSUE THREAD

**Issue by paulmenzel** [systemd/mkosi#249]
Using mkosi v4-15-g9160f3e and trying to install Debian to a directory, it fails with the error below.

```
:/scratch/local$ sudo ~/src/mkosi/mkosi -d debian -t directory -o debian-sid
[…]
‣ Installing Debian complete.
‣ Assigning hostname...
‣ Assigning hostname complete.
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Resetting machine ID...
Traceback (most recent call last):
  File "/home/pmenzel/src/mkosi/mkosi", line 3689, in <module>
    main()
  File "/home/pmenzel/src/mkosi/mkosi", line 3679, in main
    build_stuff(args)
  File "/home/pmenzel/src/mkosi/mkosi", line 3538, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/home/pmenzel/src/mkosi/mkosi", line 3396, in build_image
    reset_machine_id(args, workspace.name, run_build_script, for_cache)
  File "/home/pmenzel/src/mkosi/mkosi", line 1613, in reset_machine_id
    os.unlink(machine_id)
OSError: [Errno 16] Device or resource busy: '/scratch/local/.mkosi-i978x_3d/root/etc/machine-id'
Traceback (most recent call last):
  File "/pkg/python-3.6.4-2/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/pkg/python-3.6.4-2/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/pkg/python-3.6.4-2/lib/python3.6/tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "/pkg/python-3.6.4-2/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/pkg/python-3.6.4-2/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/pkg/python-3.6.4-2/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/pkg/python-3.6.4-2/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/pkg/python-3.6.4-2/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'machine-id'
```

Accessing this file works fine though.

```
:/scratch/local$ sudo more /scratch/local/.mkosi-i978x_3d/root/etc/machine-id
dd5ea68b4f2d41a4a11d53ee71ac61d1
:/scratch/local$ findmnt /scratch/local 
TARGET         SOURCE              FSTYPE OPTIONS
/scratch/local /dev/sda2[/scratch] xfs    rw,relatime,attr2,inode64,noquota
```

**Comment by lucaswerkmeister** [comment]
Reopening per @keszybz’s comment in #250.

**Comment by shibumi** [comment]
I might run into the same issue on fedora with mkosi 5:
```
‣ Removing output files...
‣ Removing output files complete.
DISTRIBUTION:
          Distribution: arch
               Release: n/a
                Mirror: https://mirrors.kernel.org/archlinux

OUTPUT:
              Hostname: archlinux
         Output Format: tar
                Output: /srv/www/nspawn.org/public/storage/archlinux/archlinux/tar/image.tar.xz
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: yes
            Encryption: no
                Verity: no

PACKAGES:
              Packages: none
         Package Cache: none
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /root/mkosi-definitions
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: /root/mkosi-definitions/archlinux.postinst
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

HOST CONFIGURATION:
    Extra search paths: none
‣ Detaching namespace...
‣ Detaching namespace complete.
‣ Setting up package cache...
‣ Setting up package cache /srv/www/nspawn.org/public/storage/archlinux/archlinux/tar/.mkosi-whg_3k09 complete.
‣ Setting up temporary workspace.
‣ Temporary workspace in /var/tmp/mkosi-e5khxxu9 is now set up.
‣ Mounting image...
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4539, in <module>
    main()
  File "/usr/bin/mkosi", line 4535, in main
    run_verb(args)
  File "/usr/bin/mkosi", line 4507, in run_verb
    build_stuff(args)
  File "/usr/bin/mkosi", line 4333, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "/usr/bin/mkosi", line 4147, in build_image
    with mount_image(args, workspace.name, loopdev, encrypted_root, encrypted_home, encrypted_srv):
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/bin/mkosi", line 961, in mount_image
    if args.xbootldr_partno is not None:
AttributeError: 'CommandLineArguments' object has no attribute 'xbootldr_partno'
Traceback (most recent call last):
  File "/usr/lib64/python3.7/weakref.py", line 648, in _exitfunc
    f()
  File "/usr/lib64/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/lib64/python3.7/tempfile.py", line 797, in _cleanup
    _shutil.rmtree(name)
  File "/usr/lib64/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.7/shutil.py", line 436, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.7/shutil.py", line 434, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'root'
```

**Comment by krystofl** [comment]
I have the same problem, mkosi 5, Ubuntu 20.04 image

**Comment by shibumi** [comment]
@krystofl Hey I think I fixed this issue with using the newest mkosi version on github. Check it out

**Comment by tmpm697** [comment]
confirmed that I have this issue with `mkosi` in aur but does not have it with `mkosi-git` also in aur.

**Comment by tmpm697** [comment]
@shibumi Still get the issue some time with `mkosi-git`, seems like issue with `/tmp` break dues to out of disk.

How can we specify size limit of /tmp when building with mkosi, I install bunch of  packages when build with mkosi so don't expect it to break if /tmp limited at 1G for example.

**Comment by shibumi** [comment]
@tmpm697  You might have a look on this issue here: https://github.com/systemd/mkosi/issues/332

**Comment by DaanDeMeyer** [comment]
Since the linked PR was merged I think we can close this.
