### ISSUE TITLE
partitions not detected on loop device

### ISSUE THREAD

**Issue by mna** [systemd/mkosi#416]
Hello,

I tried generating a very basic image on Fedora 32 and I get this output:

```
Checking that no-one is using this disk right now ... OK

Disk /home/m/.cache/mkosi/mysql/.mkosi-xj5icij8: 1 GiB, 1075838976 bytes, 2101248 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: 4B75D284-39B1-DA45-B6F8-EC13E5DAF00F).
/home/m/.cache/mkosi/mysql/.mkosi-xj5icij8p1: Created a new partition 1 of type 'Linux root (x86-64)' and of size 1 GiB.
/home/m/.cache/mkosi/mysql/.mkosi-xj5icij8p2: Done.

New situation:
Disklabel type: gpt
Disk identifier: 4B75D284-39B1-DA45-B6F8-EC13E5DAF00F

Device                                       Start     End Sectors Size Type
/home/m/.cache/mkosi/mysql/.mkosi-xj5icij8p1  2048 2101214 2099167   1G Linux root (x86-64)

The partition table has been altered.
Syncing disks.
mke2fs 1.45.5 (07-Jan-2020)
The file /dev/loop0p1 does not exist and no size was specified.
DISTRIBUTION:
          Distribution: fedora
               Release: 32

OUTPUT:
         Output Format: gpt_ext4
                Output: /home/m/.cache/mkosi/mysql/image.raw
       Output Checksum: n/a
      Output Signature: n/a
           Output Bmap: n/a
Output nspawn Settings: n/a
           Incremental: no
             Read-only: no
        FS Compression: no
        XZ Compression: no
                 QCow2: no
            Encryption: no
                Verity: no
              Bootable: no

PACKAGES:
              Packages: none
    With Documentation: no
         Package Cache: none
           Extra Trees: none
        Skeleton Trees: none
          Build Script: none
         Build Sources: /home/m/.cache/mkosi/mysql
  Source File Transfer: none
       Build Directory: none
        Build Packages: none
    Postinstall Script: none
       Finalize Script: none
  Scripts with network: no
       nspawn Settings: none

PARTITIONS:
        Root Partition: 1.0G
        Swap Partition: (disabled)
    XBOOTLDR Partition: (disabled)
       /home Partition: (disabled)
        /srv Partition: (disabled)

VALIDATION:
              Checksum: no
                  Sign: no
               GPG Key: default
              Password: default

HOST CONFIGURATION:
    Extra search paths: none
‣ [0;1;39mDetaching namespace...[0m
‣ [0;1;39mDetaching namespace complete.[0m
‣ [0;1;39mSetting up package cache...[0m
‣ [0;1;39mSetting up package cache /home/m/.cache/mkosi/mysql/.mkosi-8i9q3dnc complete.[0m
‣ [0;1;39mSetting up temporary workspace.[0m
‣ [0;1;39mTemporary workspace in /var/tmp/mkosi-ktrxar92 is now set up.[0m
‣ [0;1;39mCreating partition table...[0m
‣ [0;1;39mCreated partition table as /home/m/.cache/mkosi/mysql/.mkosi-xj5icij8.[0m
‣ [0;1;39mAttaching image file...[0m
‣ [0;1;39mAttached image file as /dev/loop0.[0m
‣ [0;1;39mFormatting root partition...[0m
‣ [0;1;39mDetaching image file...[0m
‣ [0;1;39mDetaching image file complete.[0m
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 4539, in <module>
    main()
  File "/usr/bin/mkosi", line 4535, in main
    run_verb(args)
  File "/usr/bin/mkosi", line 4507, in run_verb
    build_stuff(args)
  File "/usr/bin/mkosi", line 4333, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "/usr/bin/mkosi", line 4143, in build_image
    prepare_root(args, encrypted_root, cached)
  File "/usr/bin/mkosi", line 883, in prepare_root
    mkfs_generic(args, "root", "/", dev)
  File "/usr/bin/mkosi", line 722, in mkfs_generic
    mkfs_ext4(label, mount, dev)
  File "/usr/bin/mkosi", line 705, in mkfs_ext4
    run(["mkfs.ext4", "-L", label, "-M", mount, dev], check=True)
  File "/usr/bin/mkosi", line 69, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mkfs.ext4', '-L', 'root', '-M', '/', '/dev/loop0p1']' returned non-zero exit status 1.
```

The problem is that, for some reason, the partitions are not detected when `losetup` is called, despite `--partscan` being specified. Debugging this a little, I found that `lsblk` did not report the partitions on `/dev/loop0`, but `fdisk -l` did. I found this article: https://unix.stackexchange.com/a/425641 and tried adding a call to `partprobe /dev/loop0` before the formatting and it did fix the issue.

Note that this is on kernel `5.6.8-300.fc32.x86_64`, and a pretty standard Fedora install (fresh install of Fed 32), although on an old laptop. This is `mkosi version 5`.

**Comment by jshap70** [comment]
running into this too on archlinux kernel: 5.6.8-arch1-1, worked a couple of weeks ago but now nothing. 

dmesg prints a concerning error about it: 
```
[ 3212.589728] loop_reread_partitions: partition scan of loop1 (/home/jshap/dev/systemd/.mkosi-3jlyker5) failed (rc=-16)
[ 3212.639508] __loop_clr_fd: partition scan of loop1 failed (rc=-16)
```

**Comment by mrc0mmand** [comment]
I stumbled upon the same issue in systemd when our Arch machines got upgraded from kernel 5.6.7 to 5.6.8, see https://github.com/systemd/systemd/pull/15682. Looks like a kernel bug, and from what I managed to test, it seems to be working again in 5.7.0, even though the warning is still there.

**Comment by mrc0mmand** [comment]
I've filed bugs for Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1830775) and Arch Linux (https://bugs.archlinux.org/task/66526) to track the issue.

**Comment by mrc0mmand** [comment]
The issue should be fixed in kernel 5.6.11 - already released on Arch and currently in testing repos for F30 - F32.

**Comment by jshap70** [comment]
this is still showing up for me on `5.6.11-arch1-1` occasionally. worked for my first mkosi command but the second one failed.

**Comment by mrc0mmand** [comment]
> this is still showing up for me on `5.6.11-arch1-1` occasionally. worked for my first mkosi command but the second one failed.
> EDIT: although the dmesg output is gone? weird...

That's indeed weird. I updated the machines where we run systemd tests to `5.6.11-arch1-1` and it hasn't failed a single time so far, even though each run uses and partitions the loop devices quite frequently.

**Comment by jshap70** [comment]
are you using the `-i` flag? it's weird, but using `mkosi` without it and everything mounts fine but with incremental builds enabled it fails to mount.

**Comment by mrc0mmand** [comment]
To be honest, I don't use `mkosi` at all in this particular part of the CI, but playing around with `mkosi` for a bit the only mount-related issue I saw is this one: 
```
# mkosi -i
...
‣ Attaching image file...
+ losetup --find --show --partscan /home/vagrant/mkosi-playground/.mkosi-xag5_5ix
‣ Attached image file as /dev/loop1.
‣ Mounting image...
+ mount -n /dev/loop1p2 /var/tmp/mkosi-79lct2uv/root -odiscard
mount: /var/tmp/mkosi-79lct2uv/root: mount(2) system call failed: File exists.
```

which appears after second invocation of `mkosi -i` when using both `mkosi.default` and `mkosi.build`.

also, for some strange reason, `/dev/loop0` just gives up on life and vanishes from the system
```
# ls /dev/loop*
/dev/loop1  /dev/loop2	/dev/loop3  /dev/loop4	/dev/loop5  /dev/loop6	/dev/loop7  /dev/loop-control
# losetup -f
/dev/loop1
```

However, after reloading the `loop` kernel module, it pops back in and `mkosi -i` works again:
```
# modprobe -r loop
# modprobe loop
# mkosi -i
...
```

Not sure if it's the same issue you're having though (and I have no idea what's going on there, either).

**Comment by DaanDeMeyer** [comment]
I can reproduce the errors from @mrc0mmand consistently with systemd's Arch mkosi config.  It only happens when specifying `-i`.

**Comment by Werkov** [comment]
FWIW, in my case the `-i` builds were failing with EEXISTS too and the loop module trick didn't work for me. I traced it down to [the mounted btrfs](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/btrfs/volumes.c?h=v5.7-rc6#n914) and my "solution" is 
```
btrfs device scan -u
```

**Comment by DaanDeMeyer** [comment]
I can confirm this fixes the issue. Sorry for not testing this earlier. Thanks @Werkov, I'll integrate this into mkosi itself.
